application:
  security:
    secretKey: ${SHC_SECURITY_KEY}
    accessTokenExpiration: 120000 # 2 minutes
    refreshTokenExpiration: 604800000 # 1 week
    admin:
      username: ${SHC_ADMIN_USERNAME}
      password: ${SHC_PASSWORD_PASSWORD}
    permittedUris:
      post:
        - "/api/v1/users"
        - "/api/v1/users/**"
      get:
        - ${springdoc.api-docs.path}
        - ${springdoc.api-docs.path}/**
        - ${springdoc.swagger-ui.path}
        - ${springdoc.swagger-ui.path}/**
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
spring:
  application:
    name: second-hand-clothes
  flyway:
    locations: classpath:/db/migration
    schemas: ${SHC_DATASOURCE_SCHEMA:second_hand_clothes}
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${SHC_DATASOURCE_URL:localhost:5432}/${SHC_DATASOURCE_DATABASE_NAME:second_hand_clothes}?currentSchema=${spring.flyway.schemas}
    username: ${SHC_DATASOURCE_USERNAME}
    password: ${SHC_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate